//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLThucTapSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntershipWithTask
    {
        public int ID { get; set; }
        public Nullable<int> InternshipID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual InternShip InternShip { get; set; }
        public virtual Task Task { get; set; }
    }
}
