//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLThucTapSinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternShip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternShip()
        {
            this.Intern = new HashSet<Intern>();
            this.IntershipWithTask = new HashSet<IntershipWithTask>();
        }
    
        public int InternshipID { get; set; }
        public string CourseName { get; set; }
        public string Note { get; set; }
        public string PersonID { get; set; }
        public string CompanyID { get; set; }
        public DateTime StartDay { get; set; }
        public int ExpiryDate { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intern> Intern { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntershipWithTask> IntershipWithTask { get; set; }
    }
}
