//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLThucTapSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class News
    {
        public int ID { get; set; }
        public string PersonID { get; set; }
        public string Header { get; set; }
        [AllowHtml]
        public string Note { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Postdate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
